#!/usr/bin/expect

set timeout -1  ;# Отключение таймаута, чтобы процесс завершился естественно
set output_file "$env(HOME)/soundness_memo.txt"

# Открытие файла для записи вывода
log_file -noappend $output_file

spawn /root/.soundness/bin/soundness-cli generate-key --name my-key
expect "Enter password for secret key"  ;# Ожидаем появления запроса на ввод пароля
send "12345678\r"

expect eof  ;# Ждем завершения команды

# Закрытие файла после записи
log_file
